//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommiersMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADV
    {
        public int Id { get; set; }
        public string AdName { get; set; }
        public string PTitle { get; set; }
        public string FPra { get; set; }
        public string SecPra { get; set; }
        public string pi_path { get; set; }
    }
}
