//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommiersMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginInfo
    {
        public System.Guid Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string LastLogin { get; set; }
        public Nullable<bool> IsActivated { get; set; }
        public Nullable<bool> IsBloacked { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> RoleId { get; set; }
    }
}
