//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommiersMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductPictures = new HashSet<ProductPicture>();
        }
    
        public int ID { get; set; }
        public Nullable<int> SupGroup { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Qnt { get; set; }
        public Nullable<double> Price { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductPicture> ProductPictures { get; set; }
        public virtual SubGroupsT SubGroupsT { get; set; }
    }
}
