//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommiersMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stor
    {
        public int ID { get; set; }
        public string StoreName { get; set; }
        public string Personalityto { get; set; }
        public Nullable<int> Person_Phone { get; set; }
        public Nullable<System.DateTime> AddingDate { get; set; }
    }
}
