//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommiersMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubGroupsT
    {
        public int Id { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string SubGroupName { get; set; }
        public Nullable<bool> IsDeletedd { get; set; }
    
        public virtual MainGroup MainGroup { get; set; }
    }
}
