//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECommiersMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Reg_Info
    {
        public Nullable<System.Guid> Id { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> userPhone { get; set; }
        public string useremail { get; set; }
        public string username { get; set; }
        public string userpassword { get; set; }
        public int RoleId { get; set; }
    }
}
